name: 🐛 Bug Report
description: Report a bug or issue with the Prolog Logic Puzzle Solver
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out this form to help us understand and fix the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm you have completed these steps
      options:
        - label: I have searched for existing issues to avoid duplicates
          required: true
        - label: I have tried the latest version of the application
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: What type of bug are you reporting?
      options:
        - UI/UX Issue
        - Puzzle Solving Logic
        - Performance Problem
        - Browser Compatibility
        - Mobile/Responsive Issue
        - Prolog Engine Error
        - Data/Content Error
        - Accessibility Issue
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened instead
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile Safari (iOS)
        - Chrome Mobile (Android)
        - Other
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser are you using?
      placeholder: e.g., 119.0.6045.105
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 11
        - Windows 10
        - macOS Sonoma (14.x)
        - macOS Ventura (13.x)
        - macOS Monterey (12.x)
        - Ubuntu/Debian
        - Other Linux
        - iOS
        - Android
        - Other
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop/Laptop
        - Mobile Phone
        - Tablet
        - Other
    validations:
      required: true

  - type: textarea
    id: console-logs
    attributes:
      label: Console Logs
      description: Any relevant error messages from the browser console (F12 → Console)
      placeholder: Paste any error messages or console output here
      render: text

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Does this happen consistently or intermittently?
        - Are there any workarounds?
        - Any specific puzzle or feature affected?
        - Screenshots or screen recordings (if applicable)

  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      description: How severe is this bug?
      options:
        - Critical (Application unusable)
        - High (Major functionality affected)
        - Medium (Minor functionality affected)
        - Low (Cosmetic or minor issue)
    validations:
      required: true

  - type: checkboxes
    id: willingness
    attributes:
      label: Contribution
      description: Are you willing to help fix this bug?
      options:
        - label: I am willing to submit a pull request to fix this bug
        - label: I can help test the fix once it's implemented
        - label: I can provide additional information if needed
